name: Android
on:
  push:
    branches:
      - master
      - "[0-9]+.[0-9]+.x"
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
    paths:
      - ".github/workflows/**"
      - "app/**"
      - "gradle/**"
      - "**.gradle"
      - "gradle.properties"
      - "gradlew"
      - "gradlew.bat"
  pull_request:
    branches:
      - master
      - "[0-9]+.[0-9]+.x"
    paths:
      - ".github/workflows/**"
      - "app/**"
      - "gradle/**"
      - "**.gradle"
      - "gradle.properties"
      - "gradlew"
      - "gradlew.bat"

jobs:
  validate-gradle-wrapper:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1

  unit-tests:
    name: Unit Tests
    needs: [validate-gradle-wrapper]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 10
      - run: ./gradlew testCoverage --no-daemon --stacktrace
      - uses: codecov/codecov-action@v1
        with:
          flags: android

  ui-tests:
    name: UI tests
    needs: [validate-gradle-wrapper]
    runs-on: macos-latest
    timeout-minutes: 30
    strategy:
      matrix:
        include:
          - android: 28
            target: default
            gradleTask: connectedFdroidDebugAndroidTest
          - android: 28
            target: google_apis
            gradleTask: connectedPlaystoreDebugAndroidTest
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 10
      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.android }}
          target: ${{ matrix.target }}
          arch: x86_64
          script: ./gradlew ${{ matrix.gradleTask }} --no-daemon --stacktrace
          emulator-options: >-
            -no-boot-anim -no-audio -no-snapshot -no-window -camera-back none
            -camera-front none -gpu swiftshader_indirect -memory 3583
      - uses: codecov/codecov-action@v1
        with:
          flags: android

  play-store-release:
    name: Play Store Release
    if: github.repository == 'ashutoshgngwr/noice' && github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    needs: [unit-tests, ui-tests]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - uses: actions/setup-java@v1
        with:
          java-version: 10
      - run: >-
          echo "$SERVICE_ACCOUNT_KEY" > service-account-key.json;
          echo "$JKS_STORE" | base64 --decode > keystore.jks;
        env:
          SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          JKS_STORE: ${{ secrets.JKS_STORE }}
      - run: bundle install && bundle exec fastlane beta
        env:
          STORE_PASSWORD: ${{ secrets.JKS_STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.JKS_ALIAS }}
          KEY_PASSWORD: ${{ secrets.JKS_ALIAS_PASSWORD }}
      - if: ${{ always() }}
        run: rm -f service-account-key.json keystore.jks
